from radio_collar_tracker_dsp2 import PingFinder

def test_import():
    assert(True)
    assert(hasattr(PingFinder, "__init__"))
    pf = PingFinder()
    assert(pf is not None)
    assert(hasattr(pf, "gain"))
    assert(isinstance(pf.gain, float))
    assert(PingFinder.gain.__doc__ != '')
    assert(hasattr(pf, "sampling_rate"))
    assert(isinstance(pf.sampling_rate, int))
    assert(PingFinder.sampling_rate.__doc__ != '')
    assert(hasattr(pf, "center_frequency"))
    assert(isinstance(pf.center_frequency, int))
    assert(PingFinder.center_frequency.__doc__ != '')
    assert(hasattr(pf, "run_num"))
    assert(isinstance(pf.run_num, int))
    assert(PingFinder.run_num.__doc__ != '')
    assert(hasattr(pf, "enable_test_data"))
    assert(isinstance(pf.enable_test_data, bool))
    assert(PingFinder.enable_test_data.__doc__ != '')
    assert(hasattr(pf, "output_dir"))
    assert(isinstance(pf.output_dir, str))
    assert(PingFinder.output_dir.__doc__ != '')
    assert(hasattr(pf, "test_data_path"))
    assert(isinstance(pf.test_data_path, str))
    assert(PingFinder.test_data_path.__doc__ != '')
    assert(hasattr(pf, "ping_width_ms"))
    assert(isinstance(pf.ping_width_ms, int))
    assert(PingFinder.ping_width_ms.__doc__ != '')
    assert(hasattr(pf, "ping_min_snr"))
    assert(isinstance(pf.ping_min_snr, float))
    assert(PingFinder.ping_min_snr.__doc__ != '')
    assert(hasattr(pf, "ping_max_len_mult"))
    assert(isinstance(pf.ping_max_len_mult, float))
    assert(PingFinder.ping_max_len_mult.__doc__ != '')
    assert(hasattr(pf, "ping_min_len_mult"))
    assert(isinstance(pf.ping_min_len_mult, float))
    assert(PingFinder.ping_min_len_mult.__doc__ != '')
    assert(hasattr(pf, "target_frequencies"))
    assert(isinstance(pf.target_frequencies, list))
    assert(PingFinder.target_frequencies.__doc__ != '')
    assert(hasattr(pf, "start"))
    assert(pf.start.__doc__ != '')
    assert(hasattr(pf, "stop"))
    assert(pf.stop.__doc__ != '')
