@startuml Architecture
[RCTRun]
[RCTComms]
[radio_collar_tracker_dsp2]
[UIBSingleton]
[libuhd]
[socket]
[pyserial]
[/dev/ttyUSB0] as usb0

radio_collar_tracker_dsp2 ..> libuhd
RCTComms ..> socket
UIBSingleton ..> pyserial
pyserial ..> usb0
RCTRun ..> radio_collar_tracker_dsp2
RCTRun ..> RCTComms
RCTRun ..> UIBSingleton
@enduml